%% 代码说明
%通过贝叶斯更新函数，在问题二的背景下，该代码计算零配件1、配件2和成品的后验概率

%% 数据初始化
clc
clear

%初始化零配件的数据
%defect_rate为次品率    purchase_price为购买单价     inspection_cost为检测成本
components = struct(...
    'Part1', struct('defect_rate', 0.1, 'purchase_price', 2, 'inspection_cost', 1), ...
    'Part2', struct('defect_rate', 0.1, 'purchase_price', 8, 'inspection_cost', 1), ...
    'Part3', struct('defect_rate', 0.1, 'purchase_price', 12, 'inspection_cost', 2), ...
    'Part4', struct('defect_rate', 0.1, 'purchase_price', 2, 'inspection_cost', 1), ...
    'Part5', struct('defect_rate', 0.1, 'purchase_price', 8, 'inspection_cost', 1), ...
    'Part6', struct('defect_rate', 0.1, 'purchase_price', 12, 'inspection_cost', 2), ...
    'Part7', struct('defect_rate', 0.1, 'purchase_price', 8, 'inspection_cost', 1), ...
    'Part8', struct('defect_rate', 0.1, 'purchase_price', 12, 'inspection_cost', 2) ...
);

% 初始化半成品数据
pro_products = struct(...
    'SemiProduct1', struct('defect_rate', 0.1, 'assembly_cost', 8, 'inspection_cost', 4, 'disassembly_cost', 6), ...
    'SemiProduct2', struct('defect_rate', 0.1, 'assembly_cost', 8, 'inspection_cost', 4, 'disassembly_cost', 6), ...
    'SemiProduct3', struct('defect_rate', 0.1, 'assembly_cost', 8, 'inspection_cost', 4, 'disassembly_cost', 6) ...
);

% 初始化成品数据
final_product = struct(...
    'FinalProduct', struct('defect_rate', 0.1, 'assembly_cost', 8, 'inspection_cost', 6, 'disassembly_cost', 10, 'selling_price', 200, 'replacement_loss', 40) ...
);

% 初始化采样数据
sample_data = struct(...
    'Part1', struct('k', 5, 'n', 50), ...
    'Part2', struct('k', 10, 'n', 50), ...
    'Part3', struct('k', 8, 'n', 50), ...
    'Part4', struct('k', 3, 'n', 50), ...
    'Part5', struct('k', 7, 'n', 50), ...
    'Part6', struct('k', 2, 'n', 50), ...
    'Part7', struct('k', 6, 'n', 50), ...
    'Part8', struct('k', 4, 'n', 50), ...
    'SemiProduct1', struct('k', 6, 'n', 50), ...
    'SemiProduct2', struct('k', 9, 'n', 50), ...
    'SemiProduct3', struct('k', 5, 'n', 50), ...
    'FinalProduct', struct('k', 7, 'n', 50) ...
);

% 初始化先验参数
alpha_pro = 1;
beta_pro = 1;

% 初始化结果数组
update_results = cell(length(fieldnames(components)) + length(fieldnames(pro_products)) + length(fieldnames(final_product)), 1);

% 合并组件、半成品和成品数据
all_items = [fieldnames(components); fieldnames(pro_products); fieldnames(final_product)];

%% 调用函数，计算具体的值
% 遍历每个项目
for i = 1:length(all_items)
    if_name = all_items{i};
    k = sample_data.(if_name).k;
    n = sample_data.(if_name).n;

    [alpha_post, beta_post] = beiyesi_update(k, n, alpha_pro, beta_pro);
    updated_theta = expected_defective_rate(alpha_post, beta_post);

    result = struct('Item', if_name, 'Updated_Defect_Rate', updated_theta);
    updated_results{i} = result;
end

% 将结果转换为表格并打印
results_table = struct2table(cell2mat(updated_results));
disp(results_table);

%% 函数定义
% 定义贝叶斯更新函数
function [alpha_post, beta_post] = beiyesi_update(k, n, alpha_prior, beta_pro)
    alpha_post = alpha_prior + k;
    beta_post = beta_pro + (n - k);
end

% 计算后验概率
function theta = expected_defective_rate(alpha_after, beta_after)
    theta = alpha_after / (alpha_after + beta_after);
end

